# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `resume-app` directory
    directory: "resume-app"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
